data: !include data/wikitext_source.yaml
model:
  type: gpt2
  hidden_dim: 768
  num_heads: 12
  num_layers: 12
  seq_len: 1024
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
#hf_save_path: WillHeld/gpt2-lev
#hf_upload: True
trainer:
  tracker:
    - type: wandb
      project: "levanter"
      tags: [ "openwebtext", "gpt2", "itest"]

  mp: p=f32,c=bfloat16
  model_axis_size: 1
  per_device_parallelism: -1

  train_batch_size: 128
  num_train_steps: 40000
optimizer:
  learning_rate: 3E-4
  weight_decay: 0.1
  warmup: 0.01
