data:
  id: WillHeld/CommonVoice_Shuffled_Processed
  cache_dir: "gs://audio-via/processed/cv-l3-shuf"
  text_key: "text"
  train_split: "train"
  validation_split: "valid"
  tokenizer: "WillHeld/via-llama3-ps"
  processor: "openai/whisper-large-v3"
model:
  type: whisper
initialize_from_hf: "WillHeld/via-llama3-ps"
use_hf_model_config: true
trainer:
  tracker:
    - type: wandb
      project: "levanter"
      tags: [ "cv", "via"]

  steps_per_eval: 500
  mp: p=f32,c=bf16
  model_axis_size: 1
  per_device_parallelism: -1
  train_batch_size: 512
  num_train_steps: 4300
  checkpointer:
    base_path: gs://audio-via/levanter-tpu-via-cv/lev_checkpoints
    save_interval: 60m
optimizer:
  learning_rate: 2.5E-5
  weight_decay: 0.1
  warmup: 0.01
via_init: True
hf_save_steps: 500
